services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: furious_duck_prometheus_dev
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=https://dev.dsp5-archi-o24a-g2.fr/prometheus"
      - "--web.route-prefix=/prometheus"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
      - prometheus_data_dev:/prometheus
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.prometheus-dev.rule=Host(`dev.dsp5-archi-o24a-g2.fr`) && PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus-dev.entrypoints=websecure"
      - "traefik.http.routers.prometheus-dev.tls=true"
      - "traefik.http.routers.prometheus-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.prometheus-dev.loadbalancer.server.port=9090"

volumes:
  prometheus_data_dev:

networks:
  traefik_proxy:
    external: true
