services:
  backend:
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.backend-dev.rule=(Host(`dev.dsp5-archi-o24a-g2.fr`) || Host(`dev.dsp5-archi-o24a-g2.com`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-dev.priority=300"
      - "traefik.http.routers.backend-dev.entrypoints=websecure"
      - "traefik.http.routers.backend-dev.tls=true"
      - "traefik.http.routers.backend-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-dev.loadbalancer.server.port=5000"

  frontend:
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.frontend-dev.rule=Host(`dev.dsp5-archi-o24a-g2.fr`) || Host(`dev.dsp5-archi-o24a-g2.com`)"
      - "traefik.http.routers.frontend-dev.priority=1"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.frontend-dev.tls=true"
      - "traefik.http.routers.frontend-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=5173"

networks:
  traefik_proxy:
    external: true
