services:
  backend:
    volumes: !reset []
    ports: !override
      - "15000:5000"
    command: npm run dev

  frontend:
    volumes: !reset []
    ports: !override
      - "15173:5173"
    command: npm run dev -- --host 0.0.0.0
