sonar.projectKey=Fatima-9_furious-duck
sonar.organization=fatima-9
sonar.projectName=furious-duck

sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/.env,**/.env.*,**/docker-image-backups/**,frontend/src/test/**
sonar.test.inclusions=backend/tests/**/*.js,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
