sonar.projectKey=Fatima-9_furious-duck
sonar.organization=fatima-9
sonar.projectName=furious-duck

sonar.sources=backend,frontend/src
sonar.tests=backend/tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/.env,**/.env.*,**/docker-image-backups/**
sonar.test.inclusions=backend/tests/**/*.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
